More verbose logging Make sure that the regular branch is also rolled back if there are no unique commits

diff --git a/downloadbuild b/downloadbuild
--- a/downloadbuild
+++ b/downloadbuild
@@ -36,61 +36,41 @@ downloadbranch() {
 
 	# Rebase against the acquired hash if necessary
 
-	echo "Checking to see if we need to rebase against $BASE_BRANCH"
 	BASE_HASH=$(git log -1 --pretty='%H' $BASE_BRANCH)
 
-	if [ "$BASE_HASH" != "$NEW_BASELINE" ]; then
-		NEEDS_STASH=$(git status -s | grep -v '??')
+	if [ "$BASE_HASH" == "$NEW_BASELINE" ]; then
+		echo "${BASE_BRANCH} matches ${NEW_BASELINE}"
+		return 0
+	fi
 
-		if [ "" != "$NEEDS_STASH" ]; then
-			git stash
-		fi
+	echo "$BASE_BRANCH does not match ${NEW_BASELINE}"
 
-		if [ "$CURRENT_BRANCH" != "$BASE_BRANCH" ]; then
-			git checkout -f $BASE_BRANCH
-		fi
+	NEEDS_STASH=$(git status -s | grep -v '??')
 
-		if git merge-base --is-ancestor $CURRENT_HASH $NEW_BASELINE; then
-			git merge --ff-only $NEW_BASELINE
-		else
-			local CLOSEST_COUNT=$(git log --pretty='%H' ${NEW_BASELINE}..${CURRENT_HASH} | wc -l)
+	if [ "" != "$NEEDS_STASH" ]; then
+		git stash
+	fi
 
-			for remote in $(git remote); do
-				local ANCESTOR=$(git for-each-ref --format='%(refname)' refs/remotes/ | grep "/${remote}/${BASE_BRANCH}$" | cut -d'/' -f 3,4)
+	if [ "$CURRENT_BRANCH" != "$BASE_BRANCH" ]; then
+		git checkout -f $BASE_BRANCH
+	fi
 
-				if [ "" == "$ANCESTOR" ]; then
-					continue
-				fi
+	resetbasebranch
 
-				local COUNT=$(git log --pretty='%H' ${ANCESTOR}..${CURRENT_HASH} | wc -l)
+	REBASE_STATUS=$?
+	CURRENT_HASH=$(git log -1 --pretty='%H')
 
-				if [[ $COUNT -lt $CLOSEST_COUNT ]]; then
-					CLOSEST_COUNT=$COUNT
-				fi
-			done
+	if [ "$CURRENT_BRANCH" != "$BASE_BRANCH" ]; then
+		git checkout $CURRENT_BRANCH
+	fi
 
-			if [[ 0 -eq ${CLOSEST_COUNT} ]]; then
-				git reset --hard $NEW_BASELINE
-			else
-				git rebase $NEW_BASELINE
-			fi
-		fi
+	if [ "" != "$NEEDS_STASH" ]; then
+		git stash pop
+	fi
 
-		REBASE_STATUS=$?
-		CURRENT_HASH=$(git log -1 --pretty='%H')
-
-		if [ "$CURRENT_BRANCH" != "$BASE_BRANCH" ]; then
-			git checkout $CURRENT_BRANCH
-		fi
-
-		if [ "" != "$NEEDS_STASH" ]; then
-			git stash pop
-		fi
-
-		if [[ 0 -ne $REBASE_STATUS ]]; then
-			echo "Failed to update base branch"
-			return $REBASE_STATUS
-		fi
+	if [[ 0 -ne $REBASE_STATUS ]]; then
+		echo "Failed to update base branch"
+		return $REBASE_STATUS
 	fi
 }
 
@@ -456,15 +436,16 @@ rebasebranch() {
 	return $EXIT_STATUS
 }
 
-rollbackbranch() {
-	git merge-base --is-ancestor $NEW_BASELINE $CURRENT_HASH
+resetbasebranch() {
+	CURRENT_HASH=$(git log -1 --pretty='%H')
 
-	if [[ 0 -ne $? ]]; then
-		return 1
+	if git merge-base --is-ancestor $CURRENT_HASH $NEW_BASELINE; then
+		git merge --ff-only $NEW_BASELINE
+		return $?
 	fi
 
-	local CLOSEST_ANCESTOR=${SHORT_NAME}
-	local CLOSEST_COUNT=$(git log --pretty='%H' ${NEW_BASELINE}..${CURRENT_HASH} | wc -l)
+	CLOSEST_ANCESTOR=${SHORT_NAME}
+	CLOSEST_COUNT=$(git log --pretty='%H' ${NEW_BASELINE}..${CURRENT_HASH} | wc -l)
 
 	for remote in $(git remote); do
 		local ANCESTOR=$(git for-each-ref --format='%(refname)' refs/remotes/ | grep "/${remote}/${BASE_BRANCH}$" | cut -d'/' -f 3,4)
@@ -474,6 +455,7 @@ rollbackbranch() {
 		fi
 
 		local COUNT=$(git log --pretty='%H' ${ANCESTOR}..${CURRENT_HASH} | wc -l)
+		echo "$(git rev-parse --abbrev-ref HEAD) differs from ${ANCESTOR} by ${COUNT} commits"
 
 		if [[ $COUNT -lt $CLOSEST_COUNT ]]; then
 			CLOSEST_ANCESTOR=$ANCESTOR
@@ -481,12 +463,33 @@ rollbackbranch() {
 		fi
 	done
 
+	if [[ 0 -eq ${CLOSEST_COUNT} ]]; then
+		echo "Resetting $(git rev-parse --abbrev-ref HEAD) to ${BASE_BRANCH} baseline because there are no unique commits"
+		git reset --hard $NEW_BASELINE
+		return $?
+	fi
+
+	if ! git merge-base --is-ancestor $NEW_BASELINE $CURRENT_HASH; then
+		git rebase $NEW_BASELINE
+		return $?
+	fi
+}
+
+rollbackbranch() {
+	git merge-base --is-ancestor $NEW_BASELINE $CURRENT_HASH
+
+	if [[ 0 -ne $? ]]; then
+		return 1
+	fi
+
+	resetbasebranch
+
 	if [ "$SHORT_NAME" == "$CLOSEST_ANCESTOR" ]; then
 		echo "$CURRENT_BRANCH is already rebased against $SHORT_NAME ($NEW_BASELINE)"
 		return 0
 	fi
 
-	echo "Detected a large deviation from the build reference commit ${NEW_BASELINE} due to rebase against ${CLOSEST_ANCESTOR}"
+	echo "Detected a deviation from the build reference commit ${NEW_BASELINE} due to rebase against ${CLOSEST_ANCESTOR}"
 	echo "Saving existing $CURRENT_BRANCH to ${CURRENT_BRANCH}-old in case of failure"
 
 	git branch -m ${CURRENT_BRANCH} ${CURRENT_BRANCH}-old
