Preserve exit status from failed rebase If we rebase, the old deploy hash is outdated, so don't use it for computing diffs

diff --git a/redeploy b/redeploy
--- a/redeploy
+++ b/redeploy
@@ -198,6 +198,8 @@ downloadbranch() {
 		BASE_HASH=$(git log -1 --pretty='%H' $BASE_BRANCH)
 
 		if [ "$BASE_HASH" != "$NEW_BASELINE" ]; then
+			rm -f .redeploy/last_deploy.txt
+
 			NEEDS_STASH=$(git status -s | grep -v '??')
 
 			if [ "" != "$NEEDS_STASH" ]; then
@@ -427,15 +429,14 @@ rebasebranch() {
 	EXIT_STATUS=$?
 
 	if [ "" != "$STASH" ]; then
-		echo "Failed to rebase against $NEW_BASELINE, restoring git stash"
-
 		if [[ 0 -ne $EXIT_STATUS ]]; then
+			echo "Failed to rebase against $NEW_BASELINE, restoring git stash"
 			git rebase --abort
+			git stash pop
+		else
+			git stash pop
+			EXIT_STATUS=$?
 		fi
-
-		git stash pop
-
-		EXIT_STATUS=$?
 	fi
 
 	return $EXIT_STATUS
