Move fixgradle to a gw wrapper Check that we are in portal source before attempting to run scripts

diff --git a/redeploy b/redeploy
--- a/redeploy
+++ b/redeploy
@@ -55,7 +55,7 @@ applychanges() {
 		pushd $folder > /dev/null
 
 		if [[ "$folder" == modules/* ]]; then
-			fixgradle && "${GRADLE_HOME}/gradlew" deploy
+			gw deploy
 		else
 			ant jar install-portal-snapshots
 		fi
@@ -72,71 +72,24 @@ applychanges() {
 	echo -n $CURRENT_HASH > last_deploy.txt
 }
 
-fixgradle() {
-	# locate the gradlew binary
+cdroot() {
+	GIT_ROOT=$PWD
 
-	GRADLE_HOME=$PWD
-
-	while [ ! -e $GRADLE_HOME/gradlew ] && [ "/" != "$GRADLE_HOME" ]; do
-		GRADLE_HOME=$(dirname $GRADLE_HOME)
+	while [ ! -e "$GIT_ROOT/.git" ] && [ "/" != "$GIT_ROOT" ]; do
+		GIT_ROOT=$(dirname $GIT_ROOT)
 	done
 
-	if [ ! -e $GRADLE_HOME/gradlew ]; then
-		echo 'Unable to find the gradlew binary'
+	if [ ! -e "$GIT_ROOT/.git" ]; then
+		echo "Unable to find version control root"
 		return 1
 	fi
 
-	# if this is a blade workspace, don't do anything
-
-	if [ -f $GRADLE_HOME/gradle.properties ]; then
-		return 0
-	fi
-
-	# a settings.gradle in the parent folder can mess us up
-
-	if [ -f ../settings.gradle ] && [ ! -f ../gradlew ]; then
-		rm ../settings.gradle
-		git update-index --assume-unchanged ../settings.gradle
-	fi
-
-	# make sure we remembered to create an app.server.$USER.properties
-
-	if [ ! -f "$GRADLE_HOME/app.server.$USER.properties" ]; then
-		echo "Missing app.server.$USER.properties"
+	if [ ! -f "$GIT_ROOT/release.properties" ]; then
+		echo "Unable to find release.properties at version control root"
 		return 1
 	fi
 
-	# make sure we have a gradle.properties in the .gradle cache and that it matches app.server.$USER.properties
-
-	ANT_LIFERAY_HOME=$(grep -F app.server.parent.dir= $GRADLE_HOME/app.server.$USER.properties | cut -d'=' -f 2)
-
-	if [ -f "$GRADLE_HOME/.gradle/gradle.properties" ]; then
-		GRADLE_LIFERAY_HOME=$(grep -F liferay.home= $GRADLE_HOME/.gradle/gradle.properties | cut -d'=' -f 2)
-	else
-		GRADLE_LIFERAY_HOME=
-	fi
-
-	if [ ! -f "$GRADLE_HOME/.gradle/gradle.properties" ] || [ "$ANT_LIFERAY_HOME" != "$GRADLE_LIFERAY_HOME" ]; then
-		pushd $GRADLE_HOME > /dev/null
-		ant setup-sdk
-		popd > /dev/null
-	fi
-
-	# if we have a "default" dependency, make sure we have the snapshot in the .m2 cache
-
-	NEEDED_ARTIFACTS=$(grep -F '"com.liferay.portal"' build.gradle | grep -F '"default"' | grep -o 'name: "[^"]*"' | cut -d'"' -f 2)
-
-	if [ "" != "$NEEDED_ARTIFACTS" ]; then
-		for artifact in $NEEDED_ARTIFACTS; do
-			artifact_version=$(grep -F "${artifact}.version" $GRADLE_HOME/.gradle/gradle.properties | cut -d'=' -f 2)
-
-			if [ ! -d "${HOME}/.m2/repository/com/liferay/portal/${artifact}/${artifact_version}" ]; then
-				pushd $GRADLE_HOME > /dev/null
-				ant start install-portal-snapshots
-				popd > /dev/null
-			fi
-		done
-	fi
+	builtin cd $GIT_ROOT
 }
 
 downloadbranch() {
@@ -341,6 +294,10 @@ getparent() {
 	return $?
 }
 
+gw() {
+	$(dirname $0)/gw $@
+}
+
 isneedscachenpm() {
 	for folder in $(cat deploy_modules.txt); do
 		if [ -f "$folder/package.json" ]; then
@@ -389,6 +346,12 @@ setopts() {
 		export GRADLE_OPTS='-Xms3g -Xmx3g -Dorg.gradle.workers.max=1'
 	fi
 }
+
+cdroot
+
+if [[ 0 -ne $? ]]; then
+	exit $?
+fi
 
 CURRENT_HASH=$(git log -1 --pretty='%H')
 
